# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"6\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nowner_name\x18\x02 \x01(\t\"N\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rflipped_image\x18\x02 \x01(\x0c\x12\x15\n\rerror_message\x18\x03 \x01(\t2=\n\x0cImageService\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=15
  _globals['_IMAGEREQUEST']._serialized_end=69
  _globals['_IMAGERESPONSE']._serialized_start=71
  _globals['_IMAGERESPONSE']._serialized_end=149
  _globals['_IMAGESERVICE']._serialized_start=151
  _globals['_IMAGESERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
